name: Deploy Nginx to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:  # 👈 REQUIRED for Azure OIDC authentication
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'  # You can specify a version if needed

      - name: Authenticate with Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group devops-rg --name devops-aks --overwrite-existing

      - name: Deploy Nginx to AKS
        run: kubectl apply -f k8s-manifests/nginx-deployment.yml
